#!/usr/bin/env python3
"""Turn the raw terminal capture in screen.txt into the landing page's hero.

The capture is 142 columns of box drawing, which is unreadable as a plain
code block: it is wider than the content column, so it either scrolls
sideways or shrinks to nine pixels. Nothing about the *content* is the
problem, so nothing about the content changes here. What this script does is
cut the capture on its pane boundaries into three <pre> blocks that CSS can
lay out — shoulder to shoulder on a wide window, stacked on a narrow one —
and tag the glyphs so the stylesheet can colour them.

Every character in the output is a character the program printed. The colour
is the site palette standing in for the terminal's ANSI, which is the one
stated deviation (see the figcaption and stylesheets/extra.css).

Usage:
    python3 tools/render_screen.py            # print the HTML
    python3 tools/render_screen.py --write    # patch it into docs/index.md
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CAPTURE = HERE / "screen.txt"
INDEX = HERE.parent / "docs" / "index.md"

BEGIN = "<!-- BEGIN tui-screen (generated by tools/render_screen.py) -->"
END = "<!-- END tui-screen -->"

# Column boundaries, read off the capture's top border: three self-contained
# boxes at 47 + 47 + 48 cells. Asserted below rather than trusted.
PANES = [
    ("soft", 0, 47),
    ("tools", 47, 94),
    ("hard", 94, 142),
]

# Pane headings, so the <pre> can carry a name without inventing one.
PANE_TITLES = {
    "soft": "SOFT · data",
    "tools": "TOOLS · models",
    "hard": "HARD · output",
}

# The program's own section headings inside a pane.
SECTION_LABELS = {
    "file(s)",
    "summary",
    "pipeline",
    "analyses",
    "table",
    "plot",
    "flow",
}

# Frame furniture: box drawing, the arrows that join nodes, the rules. Dim,
# because it is scaffolding rather than content.
FRAME_CHARS = set("─│┌┐└┘╭╮╰╯╔╗╚╝║═├┤┬┴┼┄┈╌╍▶◀▲▼◂▸")

# What the screen reader hears instead of four thousand box characters.
ARIA = (
    "The Scelo TUI screen: three panes side by side. Left, SOFT · data — "
    "book.csv at 900 rows by 7 columns after cleaning, and the agent's "
    "reading of what the columns mean. Middle, TOOLS · models — the five "
    "pipeline stages, all complete, and the chosen analysis 'Value by "
    "segment' with the runners-up beneath it. Right, HARD · output — "
    "sum_insured across line for five segments, as a table and as a bar "
    "chart, Motor highest at 87.0M. Each pane has its own chat box at the "
    "bottom."
)


class Line:
    """One row of one pane, as characters plus a class per character."""

    def __init__(self, text: str) -> None:
        self.text = text
        self.cls: list[str] = [""] * len(text)

    def mark(self, start: int, end: int, cls: str) -> None:
        for i in range(max(0, start), min(len(self.cls), end)):
            self.cls[i] = cls

    def html(self) -> str:
        out: list[str] = []
        run_start = 0
        for i in range(1, len(self.text) + 1):
            same = i < len(self.text) and self.cls[i] == self.cls[run_start]
            if same:
                continue
            chunk = html.escape(self.text[run_start:i])
            cls = self.cls[run_start]
            out.append(f'<span class="{cls}">{chunk}</span>' if cls else chunk)
            run_start = i
        return "".join(out).rstrip()


def classify(rows: list[str], pane: str) -> list[Line]:
    lines = [Line(r) for r in rows]

    for idx, line in enumerate(lines):
        text = line.text
        first, last = 0, len(text) - 1
        is_border_row = idx in (0, len(lines) - 1)

        # 1. The pane's own frame.
        if is_border_row:
            line.mark(0, len(text), "f")
            continue
        line.mark(first, first + 1, "f")
        line.mark(last, last + 1, "f")

        inner = slice(first + 1, last)

        # 2. Box drawing anywhere in the content: node cards, the composer
        #    box, the rule under the SOFT reading, the arrows in between.
        for i in range(first + 1, last):
            if text[i] in FRAME_CHARS:
                line.cls[i] = "f"

        # 3. The dot that separates clauses everywhere in this program.
        for m in re.finditer("·", text[inner]):
            line.cls[first + 1 + m.start()] = "dim"

        # 4. Backticked column names in the prose and the table title.
        for m in re.finditer(r"`[^`]+`", text[inner]):
            line.mark(first + 1 + m.start(), first + 1 + m.end(), "id")

        # 5. Slash commands are actions, not prose — the program shows them
        #    as affordances and so do we.
        for m in re.finditer(r"(?<![\w/])/[a-z]+", text[inner]):
            line.mark(first + 1 + m.start(), first + 1 + m.end(), "cmd")

        # 6. A section heading is a line that is nothing but the heading.
        body = text[inner]
        if body.strip() in SECTION_LABELS:
            start = first + 1 + (len(body) - len(body.lstrip()))
            line.mark(start, start + len(body.strip()), "lbl")

        # 7. Glyphs that carry state.
        for i in range(first + 1, last):
            ch = text[i]
            if ch == "✓":
                line.cls[i] = "ok"
            elif ch in "█▓":
                line.cls[i] = "bar"
            elif ch == "●":
                line.cls[i] = "on"
            elif ch == "›":
                line.cls[i] = "prompt"
            elif ch == "▌":
                line.cls[i] = "cur"
            elif ch == "…":
                line.cls[i] = "dim"

        # 8. The pane title wins over all of it, including its own separator.
        title = PANE_TITLES[pane]
        if title in text:
            at = text.index(title)
            line.mark(at, at + len(title), "title")
            focus = "◂ focus"
            if focus in text:
                fat = text.index(focus)
                line.mark(fat, fat + len(focus), "focus")

    return lines


def render() -> str:
    raw = CAPTURE.read_text().rstrip("\n").split("\n")
    body, keys = raw[:-1], raw[-1]

    width = len(body[0])
    if any(len(r) != width for r in body):
        sys.exit("capture rows are not all the same width; re-capture it")
    if width != PANES[-1][2]:
        sys.exit(f"capture is {width} columns, expected {PANES[-1][2]}")

    out = [
        BEGIN,
        '<figure class="tui-screen" markdown="0">',
        '  <div class="tui-screen__frame">',
        f'    <div class="tui-screen__panes" role="img" aria-label="{html.escape(ARIA)}">',
    ]
    for pane, a, b in PANES:
        rows = [r[a:b] for r in body]
        lines = classify(rows, pane)
        out.append(f'<pre class="tui-pane tui-pane--{pane}">' + "\n".join(l.html() for l in lines) + "</pre>")
    out += [
        "    </div>",
        f'    <p class="tui-screen__keys">{html.escape(keys)}</p>',
        "  </div>",
        "  <figcaption>",
        "    Colour is the one thing here that is ours. The terminal draws this in",
        "    ANSI; the panes are tinted to the site palette so that this screen and",
        "    the demo on the marketing site agree about what each stage looks like.",
        "  </figcaption>",
        "</figure>",
        END,
    ]
    return "\n".join(out)


def main() -> None:
    block = render()
    if "--write" not in sys.argv:
        print(block)
        return

    text = INDEX.read_text()
    if BEGIN not in text or END not in text:
        sys.exit(f"{INDEX} has no {BEGIN} / {END} markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    INDEX.write_text(head + block + tail)
    print(f"patched {INDEX}")


if __name__ == "__main__":
    main()
